export APPLICATION = test_rgbled
export RIOTBASE = ../../RIOT

include ../../RIOT/tests/Makefile.tests_common


USEMODULE += vtimer
USEMODULE += color
USEMODULE += rgbled

include $(RIOTBASE)/Makefile.include
