export APPLICATION = test_driver_servo
export RIOTBASE = ../../../RIOT

include ../../../RIOT/tests/Makefile.tests_common

USEMODULE += servo
USEMODULE += vtimer

include $(RIOTBASE)/Makefile.include
