export APPLICATION = test_pwm
export RIOTBASE = ../../../RIOT

include ../../../RIOT/tests/Makefile.tests_common

USEMODULE += vtimer
DISABLE_MODULE += auto_init

include $(RIOTBASE)/Makefile.include
