export APPLICATION = test_periph_spi
export RIOTBASE = ../../../RIOT

include ../../../RIOT/tests/Makefile.tests_common

USEMODULE += vtimer
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps

include $(RIOTBASE)/Makefile.include
