APPLICATION = periph_nrf_radio
include ../Makefile.tests_common

FEATURES_REQUIRED = nrf51

USEMODULE += uart0
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps
USEMODULE += vtimer
USEMODULE += nrf51

include $(RIOTBASE)/Makefile.include
