export APPLICATION = test_periph_adc
export RIOTBASE = ../../../RIOT

include ../../../RIOT/tests/Makefile.tests_common


USEMODULE += vtimer
DISABLE_MODULE += auto_init

include $(RIOTBASE)/Makefile.include
