# name of your application
export APPLICATION = test_color

# If no BOARD is found in the environment, use this default:
export BOARD ?= native

# This has to be the absolute path to the RIOT base directory:
export RIOTBASE ?= $(CURDIR)/../../../RIOT

# Change this to 0 show compiler invocation lines by default:
export QUIET ?= 1

# Define modules that are used in this application
export USEMODULE += color

include $(RIOTBASE)/Makefile.include
